quarkus:
  http:
    port: 8080
  smallrye-jwt:
    sign:
      key: "7nVyLZkIFSXx7e1t96VK3MVaGdqjaCqqIlvJ1kA1vdJ"
      algorithm: HS256
    # sign:
    #   key-location: privateKey.pem   # RS256 (production)

  datasource:
    username: vno_auth_2025
    password: "vno@auth-2025"
    jdbc:
      url: jdbc:postgresql://localhost:5432/vno_auths

# mp.jwt config
mp:
  jwt:
    verify:
      issuer: "https://example.com/issuer"
      # publickey:
      #   location: publicKey.pem

# quarkus:
#   native:
#     resources:
#       includes: publicKey.pem

# quarkus:
#   hibernate-orm:
#     schema-management:
#       strategy: create
