quarkus:
  http:
    port: 8080
  smallrye-jwt:
    sign:
      key: "7nVyLZkIFSXx7e1t96VK3MVaGdqjaCqqIlvJ1kA1vdJ"
      algorithm: HS256
    # sign:
    #   key-location: privateKey.pem   # RS256 (production)

  datasource:
    username: neondb_owner
    password: "npg_GMfXtR8H2nkK"
    jdbc:
      url: jdbc:postgresql://ep-flat-feather-a1vmt3a1-pooler.ap-southeast-1.aws.neon.tech/vno-auth

# mp.jwt config
mp:
  jwt:
    verify:
      issuer: "https://example.com/issuer"
      # publickey:
      #   location: publicKey.pem

# quarkus:
#   native:
#     resources:
#       includes: publicKey.pem

quarkus:
  hibernate-orm:
    schema-management:
      strategy: update
